#!/usr/bin/env python
"""
示例3：自定义预处理器和模板
================================
演示如何创建自定义预处理器（Preprocessor）和自定义模板，
实现nbconvert的深度定制。

运行方式: python 03-custom-preprocessor-template.py
"""

import os
import nbformat
from traitlets import List, Unicode, Bool, Int, Dict


def create_demo_notebook(path="demo_custom.ipynb"):
    """创建一个用于演示定制的Notebook"""
    nb = nbformat.v4.new_notebook(metadata={
        "kernelspec": {"name": "python3"},
        "language_info": {"name": "python"}
    })
    
    nb.cells.append(nbformat.v4.new_markdown_cell("""# 自定义预处理器和模板演示

这个Notebook用于演示nbconvert的自定义扩展能力。

## 代码示例
"""))
    
    # 带标签的code cell（用于TagRemovePreprocessor）
    cell1 = nbformat.v4.new_code_cell("""# 这段代码会被正常导出
import this
print('Hello, nbconvert!')""")
    cell1.metadata["tags"] = []
    nb.cells.append(cell1)
    
    # 带有"solution"标签的cell
    cell2 = nbformat.v4.new_code_cell("""# @solution
# 这段代码带有solution标签，可以被预处理器移除
answer = 42
print(f"答案是: {answer}")""")
    cell2.metadata["tags"] = ["solution"]
    nb.cells.append(cell2)
    
    # 带有"hide_input"标签的cell
    cell3 = nbformat.v4.new_code_cell("""# 这段代码的输入会被隐藏，只显示输出
import datetime
print(f"生成时间: {datetime.datetime.now()}")""")
    cell3.metadata["tags"] = ["hide_input"]
    nb.cells.append(cell3)
    
    # Markdown带HTML注释
    nb.cells.append(nbformat.v4.new_markdown_cell("""## 数据表格

以下是一个简单的数据表格：

| 名称 | 值 |
|------|-----|
| A | 1 |
| B | 2 |
| C | 3 |

<!-- TODO: 添加更多内容 -->
"""))
    
    # Raw cell
    nb.cells.append(nbformat.v4.new_raw_cell("<!-- 这是raw cell，直接输出 -->\n<hr>"))
    
    with open(path, "w", encoding="utf-8") as f:
        nbformat.write(nb, f)
    return path


# ============================================================
# 自定义预处理器1：基于标签移除cell
# ============================================================
from nbconvert.preprocessors import Preprocessor

class SolutionRemover(Preprocessor):
    """移除带有solution标签的cell（教师版→学生版）"""
    enabled = True
    
    def preprocess(self, nb, resources):
        new_cells = []
        for index, cell in enumerate(nb.cells):
            tags = cell.metadata.get("tags", [])
            if "solution" not in tags:
                cell, resources = self.preprocess_cell(cell, resources, index)
                new_cells.append(cell)
            else:
                print(f"  [SolutionRemover] 移除solution cell #{index}")
        nb.cells = new_cells
        return nb, resources
    
    def preprocess_cell(self, cell, resources, index):
        return cell, resources


class InputHider(Preprocessor):
    """隐藏带有hide_input标签的code cell的输入"""
    enabled = True
    
    def preprocess_cell(self, cell, resources, index):
        if cell.cell_type == "code":
            tags = cell.metadata.get("tags", [])
            if "hide_input" in tags:
                cell.metadata["transient"] = {"remove_source": True}
                print(f"  [InputHider] 隐藏cell #{index} 的输入")
        return cell, resources


class TOCGenerator(Preprocessor):
    """从Markdown标题生成目录"""
    enabled = True
    
    def preprocess(self, nb, resources):
        toc_items = []
        for index, cell in enumerate(nb.cells):
            if cell.cell_type == "markdown":
                for line in cell.source.splitlines():
                    if line.startswith("#"):
                        # 解析标题级别和文本
                        parts = line.split(" ", 1)
                        if len(parts) == 2:
                            level = len(parts[0])
                            title = parts[1].strip()
                            if level <= 3:  # 只收集1-3级标题
                                anchor = title.lower().replace(" ", "-")
                                toc_items.append({
                                    "level": level,
                                    "title": title,
                                    "anchor": anchor,
                                    "cell_index": index
                                })
        
        resources["toc"] = toc_items
        print(f"  [TOCGenerator] 提取了 {len(toc_items)} 个标题")
        
        for index, cell in enumerate(nb.cells):
            nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
        return nb, resources
    
    def preprocess_cell(self, cell, resources, index):
        return cell, resources


class WatermarkAdder(Preprocessor):
    """添加水印/版权信息到resources"""
    enabled = True
    watermark_text = Unicode("Generated by nbconvert custom pipeline").tag(config=True)
    
    def preprocess(self, nb, resources):
        resources["watermark"] = self.watermark_text
        print(f"  [WatermarkAdder] 添加水印: {self.watermark_text}")
        for index, cell in enumerate(nb.cells):
            nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
        return nb, resources
    
    def preprocess_cell(self, cell, resources, index):
        return cell, resources


# ============================================================
# 自定义过滤器
# ============================================================
def add_border_filter(text):
    """给文本添加边框"""
    lines = text.splitlines()
    width = max(len(l) for l in lines) if lines else 40
    border = "+" + "-" * (width + 2) + "+"
    result = [border]
    for line in lines:
        result.append("| " + line.ljust(width) + " |")
    result.append(border)
    return "\n".join(result)


def first_line_filter(text):
    """只取第一行"""
    return str(text).splitlines()[0] if str(text).splitlines() else ""


# ============================================================
# 自定义模板
# ============================================================
CUSTOM_TEMPLATE_DIR = "./custom_template"
CUSTOM_TEMPLATE_NAME = "myreport"

def create_custom_template():
    """创建自定义模板目录和文件"""
    template_dir = os.path.join(CUSTOM_TEMPLATE_DIR, CUSTOM_TEMPLATE_NAME)
    os.makedirs(template_dir, exist_ok=True)
    os.makedirs(os.path.join(template_dir, "static"), exist_ok=True)
    
    # conf.json
    conf_json = '''{
  "base_template": "lab",
  "mimetypes": {
    "text/html": true
  }
}'''
    with open(os.path.join(template_dir, "conf.json"), "w") as f:
        f.write(conf_json)
    
    # 自定义CSS
    css = """
body {
    font-family: 'Segoe UI', system-ui, sans-serif;
    max-width: 900px;
    margin: 0 auto;
    padding: 20px;
    background: #fafafa;
}
.toc-box {
    background: #f0f4ff;
    border-left: 4px solid #4a90d9;
    padding: 15px 20px;
    margin: 20px 0;
    border-radius: 0 8px 8px 0;
}
.toc-box h3 { margin-top: 0; color: #2c5282; }
.toc-item { padding: 3px 0; }
.toc-item.level-1 { font-weight: bold; font-size: 1.1em; }
.toc-item.level-2 { padding-left: 20px; }
.toc-item.level-3 { padding-left: 40px; font-size: 0.95em; color: #555; }
.watermark {
    text-align: center;
    color: #999;
    font-size: 0.85em;
    padding: 20px;
    border-top: 1px solid #eee;
    margin-top: 40px;
}
.code-cell { border: 1px solid #e0e0e0; border-radius: 6px; margin: 15px 0; overflow: hidden; }
.code-cell .input { background: #f7f7f7; padding: 12px; }
.code-cell .output { padding: 12px; background: white; }
"""
    with open(os.path.join(template_dir, "static", "style.css"), "w") as f:
        f.write(css)
    
    # 主模板 - 继承lab模板，但覆盖header/footer/body_start
    template_html = """{%- extends 'lab/index.html.j2' -%}

{% block header %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ resources.metadata.name | default('Notebook') }}</title>
    <style>
{{ resources.get('inline_css', '') | safe }}
    </style>
</head>
<body>
{% endblock header %}

{% block body_start %}
<div class="report-container">
{% if resources.toc %}
<div class="toc-box">
    <h3>📋 目录</h3>
    {% for item in resources.toc %}
    <div class="toc-item level-{{ item.level }}">
        {{ item.title }}
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock body_start %}

{% block body_end %}
</div>
{% if resources.watermark %}
<div class="watermark">{{ resources.watermark }}</div>
{% endif %}
{% endblock body_end %}

{% block footer %}
</body>
</html>
{% endblock footer %}
"""
    with open(os.path.join(template_dir, "index.html.j2"), "w", encoding="utf-8") as f:
        f.write(template_html)
    
    print(f"  ✓ 自定义模板已创建: {template_dir}/")
    return template_dir


def example_custom_preprocessors():
    """示例1：使用自定义预处理器"""
    from nbconvert.exporters import HTMLExporter
    from nbconvert.writers import FilesWriter
    from traitlets.config import Config
    
    c = Config()
    c.HTMLExporter.template_name = "lab"
    
    exporter = HTMLExporter(config=c)
    
    # 注册自定义预处理器
    exporter.register_preprocessor(SolutionRemover, enabled=True)
    exporter.register_preprocessor(InputHider, enabled=True)
    exporter.register_preprocessor(TOCGenerator, enabled=True)
    exporter.register_preprocessor(WatermarkAdder, enabled=True)
    
    # 注册自定义过滤器
    exporter.environment.filters["add_border"] = add_border_filter
    exporter.environment.filters["first_line"] = first_line_filter
    
    output, resources = exporter.from_filename("demo_custom.ipynb")
    
    writer = FilesWriter(build_directory="./custom_output")
    writer.write(output, resources, notebook_name="custom_report")
    print("  ✓ 自定义预处理器报告: ./custom_output/custom_report.html")


def example_custom_template():
    """示例2：使用自定义模板"""
    from nbconvert.exporters import HTMLExporter
    from nbconvert.writers import FilesWriter
    from traitlets.config import Config
    
    c = Config()
    c.HTMLExporter.template_name = CUSTOM_TEMPLATE_NAME
    c.HTMLExporter.extra_template_basedirs = [CUSTOM_TEMPLATE_DIR]
    
    exporter = HTMLExporter(config=c)
    
    # 注册预处理器（提供TOC和水印数据）
    exporter.register_preprocessor(TOCGenerator, enabled=True)
    exporter.register_preprocessor(WatermarkAdder, enabled=True)
    exporter.register_preprocessor(SolutionRemover, enabled=True)
    
    # 读取CSS内联到resources
    css_path = os.path.join(CUSTOM_TEMPLATE_DIR, CUSTOM_TEMPLATE_NAME, "static", "style.css")
    with open(css_path) as f:
        css_content = f.read()
    
    output, resources = exporter.from_filename("demo_custom.ipynb")
    resources["inline_css"] = css_content
    
    writer = FilesWriter(build_directory="./custom_output")
    writer.write(output, resources, notebook_name="templated_report")
    print("  ✓ 自定义模板报告: ./custom_output/templated_report.html")


def example_tag_remove_config():
    """示例3：使用内置TagRemovePreprocessor（通过配置）"""
    from nbconvert.exporters import HTMLExporter
    from nbconvert.writers import FilesWriter
    from traitlets.config import Config
    
    c = Config()
    # 使用内置的TagRemovePreprocessor
    c.TagRemovePreprocessor.remove_cell_tags = ("solution", "remove_cell")
    c.TagRemovePreprocessor.remove_input_tags = ("hide_input",)
    c.TagRemovePreprocessor.remove_all_outputs_tags = ("hide_output",)
    c.HTMLExporter.preprocessors = ["nbconvert.preprocessors.TagRemovePreprocessor"]
    
    exporter = HTMLExporter(config=c)
    output, resources = exporter.from_filename("demo_custom.ipynb")
    
    writer = FilesWriter(build_directory="./custom_output")
    writer.write(output, resources, notebook_name="tag_remove_report")
    print("  ✓ 标签移除报告: ./custom_output/tag_remove_report.html")


def example_no_code_report():
    """示例4：生成无代码报告（只显示输出和Markdown）"""
    from nbconvert.exporters import HTMLExporter
    from nbconvert.writers import FilesWriter
    from traitlets.config import Config
    
    c = Config()
    c.TemplateExporter.exclude_input = True          # 隐藏代码输入
    c.TemplateExporter.exclude_input_prompt = True    # 隐藏输入提示
    c.TemplateExporter.exclude_output_prompt = True   # 隐藏输出提示
    
    exporter = HTMLExporter(config=c)
    output, resources = exporter.from_filename("demo_custom.ipynb")
    
    writer = FilesWriter(build_directory="./custom_output")
    writer.write(output, resources, notebook_name="nocode_report")
    print("  ✓ 无代码报告: ./custom_output/nocode_report.html")


if __name__ == "__main__":
    print("=" * 60)
    print("nbconvert 自定义预处理器和模板示例")
    print("=" * 60)
    
    print("\n[1] 创建演示Notebook...")
    nb_path = create_demo_notebook()
    print(f"✓ 已创建: {nb_path}")
    
    print("\n[2] 创建自定义模板...")
    create_custom_template()
    
    print("\n[3] 使用自定义预处理器...")
    example_custom_preprocessors()
    
    print("\n[4] 使用自定义模板...")
    example_custom_template()
    
    print("\n[5] 使用内置TagRemovePreprocessor...")
    example_tag_remove_config()
    
    print("\n[6] 生成无代码报告...")
    example_no_code_report()
    
    print("\n" + "=" * 60)
    print("生成的文件:")
    output_dir = "./custom_output"
    if os.path.exists(output_dir):
        for f in sorted(os.listdir(output_dir)):
            fpath = os.path.join(output_dir, f)
            if os.path.isfile(fpath):
                size = os.path.getsize(fpath)
                print(f"  ✓ {f} ({size} bytes)")
    print("=" * 60)
